# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: prepare and build
        run: |
          sudo apt-get update -qq && sudo apt-get install -q -y gcc-arm-none-eabi
          mkdir build && cd build
          cmake -DAPP_NAME=blinky ../src/
          make
